name: newtronic_banking
description: A Banking App made with Flutter.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  shimmer: ^3.0.0
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  sqflite: ^2.3.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/newtronic.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/json/
    - lib/assets/lotties/